// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class AgendaItem
    {
        public const string Codename = "agenda_item";
        public const string RoomCodename = "room";
        public const string PresentationCodename = "presentation";
        public const string EndTimeCodename = "end_time";
        public const string RecordingCodename = "recording";
        public const string LocationCodename = "location";
        public const string SpeakersCodename = "speakers";
        public const string UrlSlugCodename = "url_slug";
        public const string NameCodename = "name";
        public const string StartTimeCodename = "start_time";
        public const string TrackCodename = "track";

        public IEnumerable<object> Room { get; set; }
        public IEnumerable<object> Presentation { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        public DateTime? EndTime { get; set; }
        public IEnumerable<object> Recording { get; set; }
        public IEnumerable<TaxonomyTerm> Location { get; set; }
        public IEnumerable<object> Speakers { get; set; }
        public string UrlSlug { get; set; }
        public string Name { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        public DateTime? StartTime { get; set; }
        public IEnumerable<TaxonomyTerm> Track { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}