// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class AgendaBlock
    {
        public const string Codename = "agenda_block";
        public const string AgendasCodename = "agendas";
        public const string LocationCodename = "location";

        public IEnumerable<object> Agendas { get; set; }
        public IEnumerable<TaxonomyTerm> Location { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}