// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kentico.Kontent.Delivery;
using kontent_sample_app_conference_net.Models;

namespace KenticoKontentModels
{
    public partial class Home : BaseModel
    {
        public const string Codename = "home";
        public const string SponsorsCodename = "sponsors";
        public const string BannerTextCodename = "banner_text";
        public const string EndDateCodename = "end_date";
        public const string RegistrationCodename = "registration";
        public const string DescriptionCodename = "description";
        public const string BannerImageCodename = "banner_image";
        public const string VenueCodename = "venue";
        public const string LocationCodename = "location";
        public const string SocialMediaFeedsCodename = "social_media_feeds";
        public const string StartDateCodename = "start_date";

        public IEnumerable<object> Sponsors { get; set; }
        public string BannerText { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMM. dd, yyyy}")]
        public DateTime? EndDate { get; set; }
        public IRichTextContent Description { get; set; }
        public IEnumerable<Asset> BannerImage { get; set; }
        public IEnumerable<Venue> Venue { get; set; }
        public IEnumerable<TaxonomyTerm> Location { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMM. dd, yyyy}")]
        public DateTime? StartDate { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}