// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class Registration
    {
        public const string Codename = "registration";
        public const string TicketsCodename = "tickets";
        public const string FormCodename = "form";
        public const string TitleCodename = "title";
        public const string DescriptionCodename = "description";

        public IEnumerable<object> Tickets { get; set; }
        public IEnumerable<object> Form { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}