// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class Room
    {
        public const string Codename = "room";
        public const string NameCodename = "name";
        public const string FloorCodename = "floor";
        public const string VenueCodename = "venue";
        public const string MapCodename = "map";
        public const string NumberCodename = "number";

        public string Name { get; set; }
        public IEnumerable<MultipleChoiceOption> Floor { get; set; }
        public IEnumerable<object> Venue { get; set; }
        public IEnumerable<Asset> Map { get; set; }
        public decimal? Number { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}