// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class Speaker
    {
        public const string Codename = "speaker";
        public const string LastNameCodename = "last_name";
        public const string BioCodename = "bio";
        public const string JobTitleCodename = "job_title";
        public const string PhotoCodename = "photo";
        public const string SpeakerIdCodename = "speaker_id";
        public const string FirstNameCodename = "first_name";

        public string LastName { get; set; }
        public string Bio { get; set; }
        public string JobTitle { get; set; }
        public IEnumerable<Asset> Photo { get; set; }
        public string SpeakerId { get; set; }
        public string FirstName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}