// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class Sponsor
    {
        public const string Codename = "sponsor";
        public const string WebsiteCodename = "website";
        public const string NameCodename = "name";
        public const string DescriptionCodename = "description";
        public const string LogoCodename = "logo";

        public string Website { get; set; }
        public string Name { get; set; }
        public IRichTextContent Description { get; set; }
        public IEnumerable<Asset> Logo { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}