// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class YoutubeVideo
    {
        public const string Codename = "youtube_video";
        public const string VideoIdCodename = "video_id";

        public string VideoId { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}